apiVersion: v1
kind: ReplicationController
metadata:
  name: currentweather
spec:
  template:
    metadata:
      labels:
        app: currentweather
    spec:
      containers:
        - name: currentweather
          image: luebken/currentweather-nodejs:latest
          ports:
            - name: cw-server
              containerPort: 1337
          env:
            - name: OPENWEATHERMAP_APIKEY
              valueFrom:
                configMapKeyRef:
                    name: currentweather-config
                    key: openweathermap.apikey
          livenessProbe:
            httpGet:
              path: /healthz
              port: 1337
            initialDelaySeconds: 30
            timeoutSeconds: 1
